eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ 
management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
server:
  port: 8762
spring:
  application:
    name: gsdd-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: fx-course-app
        uri: lb://fx-course-app
        predicates:
        - Path=/courses/**
#         filters:
#       - RewritePath=/courses/(?<path>.*), /$\{path}
          
