eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ 
management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
server:
  port: 8762
spring:
  application:
    name: gateway-service
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: fx-course-app
        uri: lb://fx-course-app
        predicates:
        - Path=/courses/**
#         filters:
#       - RewritePath=/courses/(?<path>.*), /$\{path}
      - id: openapi
        uri: http://localhost:${server.port}
        predicates:
        - Path=/v3/api-docs/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
       
springdoc:
  swagger-ui:
    urls:
      - name: courses
        url: /v3/api-docs/courses